### ISSUE TITLE
When using the . operator the window is stuck 

### ISSUE THREAD

**Issue by yjhtry** [ggandor/flit.nvim#13]
### Problem description

When I want to repeat using the . operator the window stuck and I have to close the window.

code.
```javascript
store.setName();   // input ct(setName   ===>  setName()     ok
store.setName(); // input .     error
```
Please watch the video

https://user-images.githubusercontent.com/39440537/209911722-51abdaec-0ba3-45d8-be4b-3bc54d75eb9c.mov

It is normal after I delete the plugin

https://user-images.githubusercontent.com/39440537/209925602-c59866c4-eeb4-44ec-bc4f-b51c0e029dcf.mov

**Comment by ggandor** [comment]
vim-repeat is required if you want to dot-repeat Leap motions (https://github.com/ggandor/leap.nvim#dependencies)
(Note: you can exit with `C-c`, no need to close the window.)

**Comment by yjhtry** [comment]
> vim-repeat is required if you want to dot-repeat Leap motions (https://github.com/ggandor/leap.nvim#dependencies) (Note: you can exit with `C-c`, no need to close the window.)

Thanks a lot, I made a stupid mistake😂
