### ISSUE TITLE
Getting an error when remapping leap

### ISSUE THREAD

**Issue by zippeurfou** [ggandor/flit.nvim#18]
Hey there,
Very nice plugin. Thanks for all your work. @ggandor.
I am setting up a new neovim configuration and would like to use your plugin.
I am using lazy.vim as my plugin manager.
You can see the configuration and the error in the screenshot.
```
...
 {‘ggandor/leap.nvim’,
    config = function()
      require(‘leap’).add_default_mappings()
      local leap = require(‘leap’)
      special_keys = {
        repeat_search = ‘<tab>‘,
        next_phase_one_target = ‘<tab>‘,
        next_target = {‘<tab>‘, ‘;’},
        prev_target = {‘<s-tab>‘, ‘,’},
        next_group = ‘<tab>‘,
        prev_group = ‘<s-tab>‘,
        multi_accept = ‘<tab>‘,
        multi_revert = ‘<backspace>’,
      }
      leap.opts.special_keys = special_keys

    end,
  },
      {
        ‘ggandor/flit.nvim’,
        dependencies = { ‘ggandor/leap.nvim’ },
        config = function()
            require(‘flit’).setup()
        end,
    }
}
...
```
<img width="1262" alt="Screenshot 2023-01-18 at 3 53 41 PM" src="https://user-images.githubusercontent.com/4520383/213292857-88ee92c6-d486-4fb6-838a-ff4b3762861c.png">
What I did was going to line 30:
press ft + <tab> to go to next.
if I do press ftf it does work as expected.
It is also interesting to see that ftf + <tab> does work.
Therefore it seems to only error if I don't press f first to go to the next occurrence.

**Comment by ggandor** [comment]
I think the problem is that you have mapped the same key (`tab`) to `next_target` and `next_group`. `next_group` takes precedence, and you get the error reported in #17 (pending fix).

**Comment by zippeurfou** [comment]
Thanks. I'll close this one then since it's a duplicate. :)
