### ISSUE TITLE
slightly confused on usage 

### ISSUE THREAD

**Issue by kanishkaverma** [ggandor/flit.nvim#19]
Hey, 
sorry if this is dumb but I have a question. 
![image](https://user-images.githubusercontent.com/58015272/216875034-1d439a96-f201-4e82-92d9-b63686343f41.png)

as you can see how do I reach the characters which are in the blue/grey color rather than the bright green? 
thanks for your time. 
warmest regards,

**Comment by ggandor** [comment]
Press `<space>` (`special_keys.next_group`). Flit is just a Leap extension, users are expected to be familiar with Leap's usage, there's no point in duplicating the whole documentation, obivously :)

**Comment by kanishkaverma** [comment]
Thanks that's very helpful
