### ISSUE TITLE
How to achieve the effect in readme

### ISSUE THREAD

**Issue by rainzm** [ggandor/flit.nvim#22]
Hi, I like leap.nvim which is so beautiful very much. Thank you for your creation.
I use the latest flit.nvim and latest leap.nvim. When i type 'fl' to find all 'l' character, here is my screenshot:
![image](https://user-images.githubusercontent.com/22927169/218781107-9593af99-efc0-4f0f-b9a9-35a8cfad178e.png)
All 'l' character are marked, but i cannot jump directly to the 'l' character I want.
The screenshot in readme shows that all the searched characters are marked with different jump characters.
And the same is true for the screenshot in #19.
So how to implement this mode.

**Comment by ggandor** [comment]
`setup { labeled_modes = "nv", ... }` (= enable for normal and visual mode)

**Comment by rainzm** [comment]
Thanks, got it.
