### ISSUE TITLE
Neovim is frozen after typing 'df<char>' and '.'

### ISSUE THREAD

**Issue by rainzm** [ggandor/flit.nvim#23]
### Neovim version
0.8.3

### Plugin version
latest leap.nvim and latest flit.nvim

### Description
'vf\<char\>' works fine. Type 'df\<char\>' and label character, and then type '.' neovim will frozen like here:
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/22927169/218991950-df66586f-f3e5-4a3b-92cf-e3bb4969f74d.png">

**Comment by rainzm** [comment]
sry, this phenomenon has disappeared.

**Comment by ggandor** [comment]
https://github.com/ggandor/leap.nvim#dependencies

**Comment by rainzm** [comment]
Oh, thanks. I'm sorry and i will read the document of leap.nvim carefully.
