### ISSUE TITLE
flit makes . repeat of `cf<x>` hang

### ISSUE THREAD

**Issue by Grazfather** [ggandor/flit.nvim#30]
If I do e.g. `cf.` to change a filename up to the extension, it works fine, but when I go to the next line and hit `.` vim hangs hard, stuck in operator-pending mode.

This goes away when I disable flit.

**Comment by ggandor** [comment]
repeat.vim is a transitive dependency, you need to install it for Leap itself.

**Comment by Grazfather** [comment]
OK confirmed that that fixes the issue.

> [repeat.vim](https://github.com/tpope/vim-repeat), for dot-repeats (.) to work as intended

I suggest you say something more like, "repeat.vim needed otherwise dot-repeats will completely hang vim"

**Comment by ggandor** [comment]
Updated the docs (f60e4b3d49bb5a5e97cfffe66f2e671eb422078e).

> I suggest you say something more like, "repeat.vim needed otherwise dot-repeats will completely hang vim"

I think flit/leap just waits for input then, if you press something, it would leap as usual.

**Comment by Grazfather** [comment]
Thank you for the doc update.

I was stuck in operator-pending mode, but there was nothing that I could hit that would get me out of it, so I had to kill neovim, which lost me my changes as well.

**Comment by ggandor** [comment]
Yeah, I tried it, it indeed hangs.

> I had to kill neovim, which lost me my changes as well.

Ctrl-c always works, no need to kill Neovim.

**Comment by Grazfather** [comment]
With the doc change I think we can close this out. Thanks for the quick response.
