### ISSUE TITLE
`safe_labels` cannot be overridden in `setup`

### ISSUE THREAD

**Issue by emilBeBri** [ggandor/flit.nvim#33]
So by looking at `:h leap-config` it seems like it is safe_labels I need. I'm trying to get rid of s and S, since use those for substitute.vim, and would love to have these motions working with substitute

SO I got this, using lazy:
```


{ 'ggandor/flit.nvim', dependencies =  'ggandor/leap.nvim', 
    config = function()
    require('flit').setup {
      keys = { f = 'f', F = 'F', t = 't', T = 'T' },
      -- A string like "nv", "nvo", "o", etc.
      labeled_modes = "vno",
      multiline = true,
      -- Like `leap`s similar argument (call-specific overrides).
      -- E.g.: opts = { equivalence_classes = {} }
      opts = {safe_labels=   "f", "n", "u", "t", "/", "F", "N", "L", "H", "M", "U", "G", "T", "?", "Z" }
    }
    end
    },
```

However, s and S are still used for labels. What gives?

**Comment by ggandor** [comment]
Indeed. A workaround until I fix this is to set `require('leap').opts.safe_labels` itself.

**Comment by emilBeBri** [comment]
Ok nice thanks. Hmm so I put this at the end of my init.lua  (It belongs in a sub-file but just to check) :

```

require('leap').leap { opts = { safe_labels = {"f", "n", "u", "t", "/", "F", "N", "L", "H", "M", "U", "G", "T", "?", "Z"} } }
```
and that did not elimante the S from this example here:

```
git git git git git git git git
git git git git

```
there is still 

an S as seen here:

![](https://www.dropbox.com/s/9gr94rcew8g0pgv/scrot_2023-05-24_10-44-28.png?dl=1)

But perhaps I should just wait for the fix, been living with it so far, and this amazing plugin is totally worth it. means I can use semicolon as a leader key  for something else (sending code  to terminal) which is so nice

**Comment by emilBeBri** [comment]
ah right of course. Still got some lua learning to do. thanks.

**Comment by ggandor** [comment]
It's simply:
```
config = function()
  require('leap').opts.safe_labels = { "f", "n", "u", "t", "/", "F", "N", "L", "H", "M", "U", "G", "T", "?", "Z" }
end
```
((( Technically,
```
require('leap').setup {
  safe_labels = { "f", "n", "u", "t", "/", "F", "N", "L", "H", "M", "U", "G", "T", "?", "Z" }
}
```
would work too, but `setup` is deprecated, don't use that. )))
