### ISSUE TITLE
Greying out the search area

### ISSUE THREAD

**Issue by emilBeBri** [ggandor/flit.nvim#34]
Hi so when using [this doom-one implementation](https://github.com/romgrk/doom-one.vim)

I get that nice (and also very useful and mentally-less straining) effect of having the words before the cursos or after the cursor greyed out. 

this is not the case with  [catpuccin](https://github.com/catppuccin/nvim) and a lot of other well-known schemes, too.

I tried adding this (from the leap documentation) at the end of my init.lua to check out if that would fix it:

```

vim.cmd[[ 
autocmd ColorScheme * lua require('leap').init_highlight(true)
]]

```

It doesn’t, though. Have I misunderstood something, or is this  related to [my other bug filing](https://github.com/ggandor/flit.nvim/issues/33), e.g. where the leap functionality 'under the good' doesn't carry over to flit - thought it might.

**Comment by ggandor** [comment]
Leap doesn't use this "greywash" effect by default, so instead of calling `init_highlight` (that restores the defaults), you should set the `LeapBackdrop` highlight group (see `:help leap-highlight`) in the autocommand:
 
```lua
vim.api.nvim_create_autocmd('ColorScheme', {
  callback = function ()
    -- link = 'Comment' means "use the color of the comments" (instead of specifying the exact color)
    vim.api.nvim_set_hl(0, 'LeapBackdrop', { link = 'Comment' })
  end,
})
```
See the FAQ in the Leap README ("Greying out the search area").

**Comment by emilBeBri** [comment]
Ah ok got it. Sorry for wasting your time, now I'm all set (and hopefully others can search for this and get an answer without bothering you). thanks for an amazing plugin, really.
