### ISSUE TITLE
Dot repeat doesn't work correctly if you use a flit motion in between edits

### ISSUE THREAD

**Issue by murtaza64** [ggandor/flit.nvim#42]
Suppose you have this buffer:
```
hello, world, bear, walrus, bat
^
```
Then type `dtwfb`, you get
```
world, bear, walrus, bat
       ^
```
if you now dot repeat, expecting to delete `bear, ` with `dtw`, instead this happens:
```
world, bat
       ^
```
It "repeats" `dtb` since `b` was the last character searched for by flit. I am not sure how hard this is to fix, but I imagine the plugin can keep track of the last search that was part of an edit separately from the last motion that was used just for movement.

**Comment by ggandor** [comment]
Yep, thanks for reporting.
