### ISSUE TITLE
First tag in any other group is always unreachable

### ISSUE THREAD

**Issue by zwiebelbox** [ggandor/flit.nvim#43]
This is a minor issue since I would use leap for this use case instead of flit, but it looks like a bug.
If I have too many occurences, I can press <space> to switch to the next group of tags. However, the first tag is always 'f' or 't' and when I press it, I wont get to the tag I wanted to go and instead it goes through my search results in the first group. So the first tag of any group other than the first is always unreachable.

possible fixes:
- exclude f or t from the available tags in groups except for the first group.
- assume that I don't want to go forward through the search results after I changed groups and go to the tag directly
- start forward search from the group I switched to (my favorite)

**Comment by ggandor** [comment]
Related: https://github.com/ggandor/flit.nvim/issues/33
