### ISSUE TITLE
Getting  "bad argument #1 to 'insert'

### ISSUE THREAD

**Issue by tarsobcaldas** [ggandor/flit.nvim#5]
I'm trying to use the plugin, but whenever I try to use any of the mappings, I get the following error:

```
E5108: Error executing lua: ...share/nvim/site/pack/packer/start/flit.nvim/lua/flit.lua:116: bad argument #1 to 'insert' (table expected, got nil)
stack traceback:
        [C]: in function 'insert'
        ...share/nvim/site/pack/packer/start/flit.nvim/lua/flit.lua:116: in function 'flit'
        ...share/nvim/site/pack/packer/start/flit.nvim/lua/flit.lua:146: in function <...share/nvim/site/pack/packer/start/flit.nvim/lua/flit.lua:146>
fatal: /home/noaxp/.local/share/nvim/site/pack/packer/start/flit.nvim/lua/flit.lua: '/home/noaxp/.local/share/nvim/site/pack/packer/start/flit.nvim/lua/flit.lua' is outside repository at '/home/noaxp/.config/nvim'
```

**Comment by ggandor** [comment]
There was a breaking change in Leap itself, after updating Leap, it will presumably work.

**Comment by tarsobcaldas** [comment]
I unninstalled and reinstalled both plugins, and I'm still getting the same problefm

**Comment by ggandor** [comment]
You probably set `special_keys.next_target` and `special_keys.prev_target` to `nil` accidentally, see https://github.com/ggandor/leap.nvim/issues/66.

**Comment by timtyrrell** [comment]
> You probably set `special_keys.next_target` and `special_keys.prev_target` to `nil` accidentally, see [ggandor/leap.nvim#66](https://github.com/ggandor/leap.nvim/issues/66).

This changes fixed it for me 👍
