### ISSUE TITLE
Error when defining mappings  in leap special keys

### ISSUE THREAD

**Issue by petobens** [ggandor/flit.nvim#6]
Hi! I have the following leap/flit setup:
```lua
local leap = require('leap')

leap.setup({
    max_highlighted_traversal_targets = 20,
    safe_labels = { 'a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';' },
    special_keys = {
        -- FIXME: Using A- mappings gives errors with flit
        repeat_search = { '<enter>' },
        next_target = { '<enter>', '<A-n>' },
        prev_target = { '<tab>', '<A-p>' },
    },
})
require('flit').setup({}) -- enhanced f,F,t and T motions

-- Mappings (use default but don't map x)
leap.add_default_mappings()
vim.keymap.del({ 'x', 'o' }, 'x')
vim.keymap.del({ 'x', 'o' }, 'X')
```
If I press `f` and some char then I get the following error:
```
E5108: Error executing lua: ...share/nvim/site/pack/packer/start/flit.nvim/lua/flit.lua:25: Expected lua string
stack traceback:
        [C]: in function 'nvim_replace_termcodes'
        ...share/nvim/site/pack/packer/start/flit.nvim/lua/flit.lua:25: in function 'get_input'
        ...share/nvim/site/pack/packer/start/flit.nvim/lua/flit.lua:77: in function 'func'
        .../nvim/site/pack/packer/start/leap.nvim/lua/leap/main.lua:536: in function 'get_user_given_targets'
        .../nvim/site/pack/packer/start/leap.nvim/lua/leap/main.lua:1234: in function '_217_'
        .../nvim/site/pack/packer/start/leap.nvim/lua/leap/main.lua:1257: in function 'leap'
        ...share/nvim/site/pack/packer/start/flit.nvim/lua/flit.lua:119: in function 'flit'
        ...share/nvim/site/pack/packer/start/flit.nvim/lua/flit.lua:146: in function <...share/nvim/site/pack/packer/start/flit.nvim/lua/flit.lua:146>
```
If I remove the special_keys config section then things do work.

**Comment by ggandor** [comment]
I think the problem is this line:
```
repeat_search = { '<enter>' },
```
`repeat_search` expects a string, only `next/prev_target` can accept tables.  (Btw `<enter>` is the default repeat key, no need to specify that.)

Unrelated:
```
safe_labels = { 'a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';' },
```
`a` - what if you want to append after jumping?
`d` - ...delete something from the position you've jumped to
`g` - ...do any kind of `g` operation, like `gu`, gw` etc.

`h`, `j`, `k`, `l` raise interesting questions... one use case of `k`, `j` after jumping might be going up/down to include an empty line in the selection

**Comment by petobens** [comment]
> repeat_search expects a string, only next/prev_target can accept tables. (Btw <enter> is the default repeat key, no need to specify that.)

Ohh thanks for that. That was indeed the problem

> safe_labels = { 'a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';' },

I though the `safe_labels` options are the `labels` shown for additional matches similar to sneaks' `let g:sneak#target_labels = 'asdfghjkl;'`
I might have completely misunderstood this config option though. Basically I want my home row keys to easily jump after type `s{}{}`. Is there a better way of doing that?

Thanks for the quick reply.

**Comment by ggandor** [comment]
> I though the safe_labels options are the labels shown for additional matches similar to sneaks' let g:sneak#target_labels = 'asdfghjkl;'

Yes, and in Sneak too the target labels should be keys that are unlikely to be used right after a jump (since we automatically jump to the first target, and the next keypress can be anything).

In Leap though, you can define a separate `labels` list (for the case when there are too many matches, and we do not auto-jump), there you can use any keys ("unsafe" ones).

https://github.com/ggandor/leap.nvim/tree/847a1dcfb1a3a576860151754d95fb3b0014663e#smart-autojump
https://github.com/ggandor/leap.nvim/blob/847a1dcfb1a3a576860151754d95fb3b0014663e/doc/leap.txt#L183-L212

**Comment by petobens** [comment]
Thanks for the explantion. Feel free to close :)

**Comment by petobens** [comment]
Sorry for reopening but I'm still seeing the behaviour with
```lua
    special_keys = {
        next_target = { '<A-n>' },
        prev_target = { '<A-p>' },
    },
```
If I press something like `fp` then I get:
```
E5108: Error executing lua: ...share/nvim/site/pack/packer/start/flit.nvim/lua/flit.lua:25: Expected lua string
stack traceback:
        [C]: in function 'nvim_replace_termcodes'
        ...share/nvim/site/pack/packer/start/flit.nvim/lua/flit.lua:25: in function 'get_input'
        ...share/nvim/site/pack/packer/start/flit.nvim/lua/flit.lua:77: in function 'func'
        .../nvim/site/pack/packer/start/leap.nvim/lua/leap/main.lua:536: in function 'get_user_given_targets'
        .../nvim/site/pack/packer/start/leap.nvim/lua/leap/main.lua:1234: in function '_217_'
        .../nvim/site/pack/packer/start/leap.nvim/lua/leap/main.lua:1257: in function 'leap'
        ...share/nvim/site/pack/packer/start/flit.nvim/lua/flit.lua:119: in function 'flit'
        ...share/nvim/site/pack/packer/start/flit.nvim/lua/flit.lua:146: in function <...share/nvim/site/pack/packer/start/flit.nvim/lua/flit.lua:146>
```
If I add the: `repeat_search = '<enter>',` line then everythings works. 

>  a - what if you want to append after jumping?

I think I now understand why you say here... Is it possible to "disable" the multiline search/jumping after the first jump?

**Comment by ggandor** [comment]
Yep, by the way, if you use `setup`, you should define _all_ special keys, as it simply replaces the whole table. It's much simpler to:

```
leap.opts.special_keys.next_target = { '<a-n>' }
leap.opts.special_keys.prev_target = { '<a-p>' }
```

**Comment by petobens** [comment]
Great thanks!
